# https://render.com/docs/yaml-spec
# deploy service on render.com

# Preview Environments | Render · Cloud Hosting for Developers
# https://render.com/docs/preview-environments
# Preview environment is a temporary service and URL that
#    is created when you issue a pull request
#    and deleted when you merge or reject the PR or after a time limit

previewsEnabled: true
previewsExpireAfterDays: 2
services:
    - type: web
      name: express-hello-world
      env: node
      previewPlan: starter
      autoDeploy: true # Immediately deploy upon push to git default branch
      buildCommand: yarn
      startCommand: yarn start
      envVars:
          - key: DB_URI
            value: 'mongodb://aXelFoleY:b3v3rlyHi77s*C0p@portal-ssl2194-11.mpcssurveys18.3038111348.composedb.com:16918,portal-ssl2470-10.mpcssurveys18.3038111348.composedb.com:16918/surveys-test?useUnifiedTopology=true&tls=true&useNewUrlParser=true'
          - key: NODE_ENV
            value: production
          - key: DB_URI
            value: production-uri
          - key: DB_PASS
            generateValue: true
          - key: DB_USER
            sync: false
# envVarGroups:
#     - name: example
#       envVars:
#           - key: simple-key
#             value: simple-value
#     - name: production
#       envVars:
#           - key: NODE_ENV
#             value: production
#           - key: DB_URI
#             value: production-uri
#           - key: DB_PASS
#             generateValue: true
#           - key: DB_USER
#             sync: false
#     - name: test
#       envVars:
#           - key: NODE_ENV
#             value: test
#           - key: DB_URI
#             value: test-uri
#           - key: DB_PASS
#             generateValue: true
#           - key: DB_USER
#             sync: false
