# https://render.com/docs/yaml-spec
# deploy service on render.com

# render.yaml does not support variable interpolation.
# The best way to accomplish this is to pair environment variables
# with a build or start script that does the interpolation for you.

# Preview Environments | Render · Cloud Hosting for Developers
# https://render.com/docs/preview-environments
# Preview environment is a temporary service and URL that
#    is created when you issue a pull request
#    and deleted when you merge or reject the PR or after a time limit

previewsEnabled: true
previewsExpireAfterDays: 2
services:
    - type: web
      name: preview-express-hello-service
      env: node
      previewPlan: starter
      autoDeploy: true # Immediately deploy upon push to git default branch
      healthCheckPath: /app_status
      buildCommand: yarn
      startCommand: source run.env && yarn start
      envVars:
          - key: APP_NAME
            value: exec-dash
          - key: NODE_ENV
            value: production
            previewValue: test
#           - fromGroup: test
# envVarGroups:
#     #     - name: example
#     #       envVars:
#     #           - key: simple-key
#     #             value: simple-value
#     #     - name: production
#     #       envVars:
#     #           - key: NODE_ENV
#     #             value: production
#     #           - key: DB_URI
#     #             value: production-uri
#     #           - key: DB_PASS
#     #             generateValue: true
#     #           - key: DB_USER
#     #             sync: false
#     # exec-dash-two test environment group
#     - name: test
#       envVars:
#           - key: NODE_ENV
#             value: test
#           - key: DB_NAME
#             value: executiveDashboardDev
#           - key: DB_USER
#             value: mikel.leu
#           - key: DB_PASS
#             # value: '%40e$bu$17' #secret
#             sync: false
#           - key: DB_SERVER
#             value: portal-ssl1052-28.metropcs2017.aesbus.composedb.com:23865,portal-ssl977-29.metropcs2017.aesbus.composedb.com:23865
#           - key: DB_OPTIONS
#             value: 'tls=true&retryWrites=false'
